spring:
  datasource:
    initialization-mode: always
    url: "jdbc:mariadb://localhost:3306/authsvr"
    username: "mslim"
    password: "mslim8803"
    dbcp2:
      test-while-idle: true  
      validation-query: "SELECT 1"
  thymeleaf:
    cache: false

logging:
  level:
    com.wsproject.authsvr: debug
    
custom:
  api-base-uri: http://localhost:5555/api
  jwt-signkey: "{cipher}73e168f04e3f17ce08518b76f28cbf303a18b6b8700cfb0fcfa1f338f7fc56b6"