zuul:
  prefix: /api
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
       
logging:
  level:
    com.wsproject.zuulsvr: debug
    
spring:
  zipkin:
    base-url: http://localhost:9411