spring:
  datasource:
    url: "jdbc:mariadb://mslim-test-db.ch6vyze6a3fs.ap-northeast-2.rds.amazonaws.com:3306/ws_service"
    username: "ws_service"
    password: "{cipher}7978eb95dd6c1a6495b162e549f0da8d50896d8045b6a0cb9f2e6928f92f913d"
    dbcp2:
      test-while-idle: true  
      validation-query: "SELECT 1"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.internal.EhCacheRegionFactory
        generate_statistics: true
    show-sql: true   
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 100
      
logging:
  level:
    com.wsproject.wsservice: debug
    
custom:
  api-private-base-uri: http://zuulsvr:5555/api
  api-public-base-uri: http://localhost:5555/api
  jwt-signkey: "{cipher}73e168f04e3f17ce08518b76f28cbf303a18b6b8700cfb0fcfa1f338f7fc56b6"