spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/ws_service"
    username: "mslim"
    password: "{cipher}b782b7d252d96a69b616427af9d0e9d689318d28d1ac6cbea4fb26e40233dee4"
    dbcp2:
      test-while-idle: true  
      validation-query: "SELECT 1"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.internal.EhCacheRegionFactory
        generate_statistics: true
    show-sql: true   
    hibernate:
      ddl-auto: update
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 100
  zipkin:
    enabled: false
    
logging:
  level:
    com.wsproject.wsservice: debug
    
custom:
  api-private-base-uri: http://localhost:5555/api
  api-public-base-uri: http://localhost:5555/api
  jwt-signkey: "{cipher}73e168f04e3f17ce08518b76f28cbf303a18b6b8700cfb0fcfa1f338f7fc56b6"