spring:
  datasource:
    url: "jdbc:mariadb://mslim-test-db.ch6vyze6a3fs.ap-northeast-2.rds.amazonaws.com:3306/batch_service"
    username: "batch_service"
    password: "{cipher}7978eb95dd6c1a6495b162e549f0da8d50896d8045b6a0cb9f2e6928f92f913d"
    initialization-mode: always
    dbcp2:
      test-while-idle: true  
      validation-query: "SELECT 1"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true   
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 100
          
logging:
  level:
    com.wsproject.batchservice: debug
    
custom:
  api-base-uri: http://zuulsvr:5555/api
  client-id: "{cipher}8792efbb10ee0e7637154a565b069234298b3cd2cab887db6031e9fcbc36a099"
  client-secret: "{cipher}a9aebad181d46568fb4b19d1eb5028108ba691bdeafafcf4afd23f7090e34118bdfef9adbb4793c5a56c3ede06a8e95e2860d512b263e8b0dab580ca4fe9d3a3"
  admin-password: "{cipher}948c32ce82b49b12d8380f53792467d86c862fb5b6e6dbb8e3489977b185ed65bd498153939521ee3da70eddff4a3be7282f1398201db0320cf0647861c5d696"